# Generated by Django 5.2.8 on 2025-12-29 20:41

import django.contrib.postgres.indexes
import django.db.models.deletion
import django_ltree_field.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(default=1, editable=False)),
                ('path', django_ltree_field.fields.LTreeField(editable=False, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='employers.department')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(db_index=True, max_length=255, verbose_name='Должность')),
                ('hired_at', models.DateField(db_index=True, verbose_name='Дата приема на работу')),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Зарплата')),
                ('structure_path', django_ltree_field.fields.LTreeField(db_index=True, editable=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employers.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=django.contrib.postgres.indexes.GistIndex(fields=['path'], name='employers_d_path_11a447_gist'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.GistIndex(fields=['structure_path'], name='employers_e_structu_be1c2c_gist'),
        ),
    ]
